### PR TITLE
Add PreloadWebpackPlugin

### PR DESCRIPTION
**Pull request by aofdev**
Add package PreloadWebpackPlugin default is it good ?

### CODE REVIEW

**Comment by addyosmani** [comment]
So we currently perform a simpler version of this pattern using preload/prefetch over in https://github.com/vuejs-templates/pwa/blob/master/template/index.html#L26. I'm not opposed to adding in this plugin (it's my own) but we should be clear what the benefit is here.

**Comment by aofdev** [comment]
I have not used any function yet.
I just wanted to help or reinforce vuejs-templates/pwa development.

**Comment by codeofsumit** [comment]
@addyosmani are webfonts currently inserted to load with `preload` attribute?

**Comment by jeffposnick** [comment]
Hello @codeofsumit—Thanks for your contribution. Unfortunately, I don't think we could use the code in your PR as-is.

I've opened https://github.com/vuejs-templates/pwa/issues/113 to track some of the changes that I think are necessary to get the equivalent behavior with `preload-webpack-plugin`.

I'm going to close this PR for now and we can revisit in a fresh PR with a different config if and when `preload-webpack-plugin` is modified.

**Pull request closed without merging**
