### PR TITLE
Add support for the video poster attribute

### PR DESCRIPTION
**Pull request by RomansBermans**

### CODE REVIEW

**Comment by jeffposnick** [comment]
As per the [Contributing guide](https://github.com/vuejs-templates/pwa#contributing), could you please address this by filing a PR to modify the [upstream source](https://github.com/vuejs-templates/webpack/blob/develop/template/build/vue-loader.conf.js#L18) first, at which point we can make the corresponding change to this repo?

**Comment by RomansBermans** [comment]
Sorry @jeffposnick I missed that part of the README. I just have created a PR at the upstream source https://github.com/vuejs-templates/webpack/pull/1123

**Comment by jeffposnick** [comment]
No worries—it comes up a lot, so we just added it to the README 😄

**Comment by RomansBermans** [comment]
@jeffposnick I can see that it has been merged into the upstream source https://github.com/vuejs-templates/webpack/pull/1123

**Review by jeffposnick — APPROVED** [review]

**Comment by jeffposnick** [comment]
Thanks!

**Pull request merged**
