### PR TITLE
fix Es6 code issue.

### PR DESCRIPTION
**Pull request by zhenhappy**
This file is not transpiled, so we should stick to ES5

### CODE REVIEW

**Comment by anubhav7495** [comment]
`const` is supported in node since v4 and above, so i don't see how is this a problem?

**Comment by zhenhappy** [comment]
@anubhav7495 I found this program in iOS9 device, so this code is run in browser, not run in node

**Comment by zhenhappy** [comment]
the old mobile device is not supported `const`

**Comment by Naramsim** [comment]
@zhenhappy I don't think you spin up a dev-server from an iPhone

**Comment by zhenhappy** [comment]
you can see this link [https://github.com/vuejs-templates/webpack/commit/993717604d15b240e07d5da8d55b815452d11581#diff-cac48dfa87b0049be0ff4be8f3d9f6dc](https://github.com/vuejs-templates/webpack/commit/993717604d15b240e07d5da8d55b815452d11581#diff-cac48dfa87b0049be0ff4be8f3d9f6dc)

**Comment by anubhav7495** [comment]
Looks good. would test it locally once before merging. Thanks @zhenhappy

**Comment by LinusBorg** [comment]
(Note: I merged the fix on the webpack template)

This file is added to the bundle that is served to the client by the dev-server - and since it's not transpiled, will break on any brower or device that doesn'T support ES6.

So changing it to var is the correct fix here.

**Comment by anubhav7495** [comment]
@LinusBorg But any such browser will also not support service-workers and developing on such a browser for a pwa is quite odd, do you think?

**Pull request merged**
